// This file was generated by Prisma and assumes you have installed the following:
/** biome-ignore-all lint/style/useNodejsImportProtocol: > */
// import "dotenv/config";
// import { readFileSync } from "fs";
// import path from "path";
// import { defineConfig, env } from "prisma/config";

// // 1. Build full schema first
// const schemaString = [
//   readFileSync(path.join(process.cwd(), "prisma/schema.prisma"), "utf8"),
//   readFileSync(path.join(process.cwd(), "prisma/enum.prisma"), "utf8"),
//   readFileSync(path.join(process.cwd(), "prisma/user.prisma"), "utf8"),
//   readFileSync(path.join(process.cwd(), "prisma/subscription.prisma"), "utf8"),
//   readFileSync(path.join(process.cwd(), "prisma/trip.prisma"), "utf8"),
// ].join("\n");

// // 2. TEMPORARY — log raw output
// console.log("===== FINAL MERGED SCHEMA =====");
// console.log(schemaString);
// console.log("================================");

// export default defineConfig({
//   schema: schemaString,
//   migrations: {
//     path: "prisma/migrations",
//   },
//   datasource: {
//     url: env("DATABASE_URL"),
//   },
// });
import { defineConfig, env } from "prisma/config";
import "dotenv/config";
import path from "path";

export default defineConfig({
  schema: path.join(__dirname, "prisma", "schema.prisma"),
  migrations: {
    path: path.join(__dirname, "prisma", "migrations"),
  },
  datasource: {
    url: env("DATABASE_URL"),
  },
});
